# Required: When not using ingress.enabled=true then must use Loadbalancer for deployment spec to render.
service:
  type: LoadBalancer
rconWeb:
  isAdmin: true
  game: minecraft
  passwordExistingSecret: minecraft-rcon
  passwordKey: rcon-password
  rconHost: minecraft-rcon.game-servers.svc.cluster.local
  rconPort: 25575
  rconPasswordExistingSecret: minecraft-rcon
  rconPasswordKey: "rcon-password"
extraEnv:
  TZ: Australia/Melbourne
# Required: Cannot install jq as part of startup script.
securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
