minecraftServer:
  serverName: Wildfire Minecraft Server
  eula: "TRUE"
  type: PAPER
  version: LATEST
  pluginUrls:
    - https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
    - https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
  difficulty: peaceful
  maxPlayers: 4
  maxTickTime: -1
  gameMode: survival
  hardcore: false
  pvp: false
  worldSaveName: world
  onlineMode: true
  rcon:
    enabled: true
  motd: "Welcome to Minecraft on Kubernetes!"
  playerIdleTimeout: 10
  cheats: true
  enableLanVisibility: true
  defaultPermission: operator
  enableSSH: true
  extraPorts:
  - name: geysermc
    containerPort: 19132
    protocol: UDP
    service:
      enabled: true
      port: 19132
  overrideServerProperties: true
  removeOldMods: false

resources:
  requests:
    memory: 2Gi
    cpu: 1

persistence:
  dataDir:
    enabled: true
    existingClaim: minecraft
