minecraftServer:
  serverName: Wildfire Minecraft Server
  eula: "TRUE"
  type: PAPER
  version: LATEST
  pluginUrls:
    - https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
    - https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
  spigetResources:
    - 19254 # ViaVersion
    - 9089  # EssentialsX
    - 34315 # Vault
    - 28140 # LuckPerms
    - 32748 # Set Home
    - 390   # Multiverse-Core
  maxPlayers: 4
  maxTickTime: -1
  gameMode: survival
  hardcore: false
  pvp: false
  worldSaveName: world
  onlineMode: true
  rcon:
    enabled: true
  motd: "Welcome to Minecraft on Kubernetes!"
  playerIdleTimeout: 10
  cheats: true
  enableLanVisibility: true
  defaultPermission: operator
  enableSSH: true
  serviceType: LoadBalancer
  extraPorts:
  - name: geysermc
    containerPort: 19132
    protocol: UDP
    service:
      enabled: true
      embedded: true
      port: 19132
  - name: geysermc-rcon
    containerPort: 25575
    protocol: UDP
    service:
      enabled: true
      embedded: true
      port: 25575
  overrideServerProperties: true
  removeOldMods: false

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"

resources:
  requests:
    memory: 2Gi
    cpu: 1
    ephemeral-storage: "1Gi"

persistence:
  dataDir:
    enabled: true
    existingClaim: minecraft

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
