apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-cache
  namespace: home-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: truenas-iscsi-csi
