apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secret
    namespace: home-system
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:lGjZAugX9MG6,iv:DsqtwMmqzUVQV3iJTnuqin4ux0QBxHbaAgE01u+Lnbk=,tag:VuoT5yvwtghsw1uaLXsLQA==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:hY/nQ8R4B4th,iv:WbQFH+GYNZauUpoPeG7t5ZlKwu3Jz7OnmAoaD+rHLqk=,tag:nEkltEWNWw1edyXiPIauxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-15T20:44:08Z"
    mac: ENC[AES256_GCM,data:PCoTO6n4jxQNkFVSMxUVi5rnB4vv7P7MTl/8qejQSQBpA/pWL/ryR/nOj5lVnsTptOgxpUEZVN0CqLUxWOQ3puFfIhnEVZh+E/yjiHiIVfQUgFCOs5D6Y1r8cfNYWr5Ejre4DqhmkZBBRG5XHOTVMU3rY0LtUgfVUahWtN2uo24=,iv:Y9/5UDVGwhTjUuJYXWoqQ1VxCRfat5DZLutdD3vYVvo=,tag:eDNn+4HeGYvUixRe3F144Q==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
