apiVersion: v1
kind: Secret
metadata:
    name: github-app-secret
    namespace: actions-runner-system
type: Opaque
data:
    github_app_id: ENC[AES256_GCM,data:7N5XiDbf,iv:Nfd1BDIGfLa7fnUoxZLTYwpoeH2enyoPoXPkTMiMiac=,tag:WOx+lbnkxcbrnFOpyPN4Sw==,type:int]
    github_app_installation_id: ENC[AES256_GCM,data:xWFLwQlW+h4=,iv:T+mqsh1qp/CRXi9pHxNiQ0/wsII2g5Onp/BdLC84ArY=,tag:6zwPW3ZD13q7ID1RU3siDg==,type:int]
    github_app_private_key: ENC[AES256_GCM,data:/5Du9wfAusPZAHDXq135jDUKA5n3yDXpk3pAR1XB9spoY/W06Ofb2HYbmm5gadrABrgS4SIzoBolUs/kcvXqIQgw49SRCdxKe89Q0H/57JCAAqp7Vml5/kQy1r9U3MQ8HFA1mIsFqCa1YQn9UWshIkS8itrf43RkNWRLpDPgur7J3/vn9yfnI9s+c15DfqV8Bx3Agzj04oZ/ZW7VC1H+oTTJT0FCXrobrNwansB8+Z0K7EKXmNSOwGqNo8yrCA9BbX8HhNrCJu/k1peCxaMm0KuqqufnQ5QJqvwXhvAoeuVvL3n68L1FhGI38BZaEKqWvsjOBR7TgafVZUY4O65Hp6NLGpsE+3pgBPX08LUWa6Ustc2rIv4EWpRts09T0WR/LaVy2iR5HkDkGtrdzji7cBt9DBT0UZsRW7ytckJrdhpiD54/dStAjxpdAuyDXUrq/RfZphIRB0TXGLtObcKwJ2MYNFHEh/rtVf7jYlHtc5uXR2QEZSMhgfjHjn8bLXPUIxrmccItrOfdXDSks3LtWh6g4/CXjspBdnhu1DgJo2QTsA31UgTmhjzVLJVH2PpabK1i+1F62UtitC2VxcMnLta0VweYsPY+OXOUnnaj6E6MYu+tRUFAkQFVsSdbVeCk1HRLEXl4zY08LE177yKGx0QwtRoiUQb6sFWlhY77GqYmmqhRHRW4aD+xM2hw2LX+yD5/vgOTt4YHbohVLsZ009PmAkm/50KpDALoxwRiWdwSvs4+SGxQ/XF3nMqI0n5EcODc9AWdbMYNMnjwbxc9EWHLd7rQhtNBfDMA7TEXHlHQwiEk0D+jEAQ/Sb8CxKgP+Q5FnTc2f/TxX1T/OjTy8XiIDjk0dzBADforNt42EtVoXiPizCx0y8wTgfffGsvPko3F6PQ6INL5sCBk+pAflLQVZeamjeoHHdc76q2o+GIbNctVYnqrOo4jz6JkCEE8vTBruaAu4MiU1SN8n06fVH/eh1vd1UTTolV+e42CaDFLXhNFCfEkwTyOhAbj146/sGuCu1z6+TKJ2/M4AQjjslaOrmdFlZNCYkk+GROkKHaEoBa91jl/AwSB4J3/tN85//pm2Cue6umKuSNGonkv+Proq/cady+o0jrVNO0PADwI2LQXiIdZcVAiunXtD9E9mmEOfKzYuXqITfM33xFKWslYe5H3Yn/fxdY2KkY0T68t9LxQmOMB8+rFX2opIUt0SI778uKixIscJq53Ci4YkH3Je7eXloKMwbcSN3v2VYtFYUiFeCL6gBsjkEUenMIjFTzMpWl8OTETJigTWECP3sqm9YJa3nAu8kfjPehcHr0lePMdROIjGPUDtGTDyqHeQns/xVwBefHutOZ5ZRc0BLIVQUOSEZNbR762SSmj7hV7lc8afi9RzVCjFMNX9pQQzCacZK10CFDb3RvUm0o/g6CSfBsUjrTxhtFlVCSBhXNvKj5yfZj40QmIM7D5SizUxk1rMidYhQcibLcKsKjC0gto22M8oYuRITQErxjzTXfhm1kx/uMN0yhp0yH9hy1DViZ4j6DAn3MG6Nw5ndhPS8v8J2gG80tblRAT6p2hWwZuENWa93Y7kNdGZucGjlt6VBLylZERPhNBX92/i0oDkGGb0Vj4QEyTo8ihcC+Hrg/NdVN01BPc0btw6yi81CIcJE2hV7CGAcyh7+0peJ1XXoULd7ZUlXMdYE2XV6qxLnzaHwgtEGBsUSyGeT381LZyR39/uTZbEfJI+XtQfdAYOG3oYjoJ8t/UVaUnaWoomb/cyovvrpScBzg2u2ehtAt+ed1dZnkaGmoeMnSa0Ry4gqbaS6dkhTAK8+odxHpaxFJPwUTDZ22yf2p6Z/dMOKHLS3DN5XB3+L/L2J6qbBcbFd+WyNq7FhzgNJNG/Xo1GE5Nu1CNMLO/XgJAm/KPRiIMN/3E6YRG6SJlaVe2/+fwuQnZXpDTO0kDxgr8cJX2b3xV+T/dipJyr/l/OhcfaREhlrCKKCwuefLWbk1iFeH36vSPO826IxIMLPGszmBC1PEHS7mBZJdtDisjhixwN7dPgPFDm3KoROvBNXyTLjT/8vSfyCdq8fENSmw+IIERFK4dAb3ro5FHlQtnyMPY+r5IfbS+vQkbiGK0VojKADTrizVyFxMN+843dNfzsz3R5m4hjGELBFKNAqi2GXj08FHTHuXbwmvkJuvSQkSNUgMecu0cX3uLeCuwc/a2RiXZGl4SJgfxbzt5ucuEfA==,iv:bBHVZ7PbiryrVPH1ZrYm0VenzuUNrZ+SEI2cxj8Mrx8=,tag:3aBl+nIGUcQT8V5rWWsGwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-08T08:44:42Z"
    mac: ENC[AES256_GCM,data:UBhLT2PUnOpm9Tjz7KuoB3Q6Vz9f2g4MjXkROSwGFwjmhtmYIRoQdGmX28AOxeyXRF/MZiUugBvOjs0Z48ttx6D4parB2oie1wSSmFL0WZnVGi/gHMXNPWtxng0ZZic4l5oTfFPj/WzW3YPueIArm1Zvk0FvjcknHK/5uN/XJ20=,iv:3//LWWjSl1x02CpTncNthHOSJmgCQhlX0Ix+DRPnAd4=,tag:/R/HAXr6vVFP0Q5gn1lZuQ==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
