---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflare-ddns
  name: cloudflare-ddns
  namespace: network-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - env:
            - name: CF_APITOKEN
              valueFrom:
                secretKeyRef:
                  key: api-token
                  name: cloudflare-ddns
            - name: CF_ZONES
              valueFrom:
                secretKeyRef:
                  key: zones
                  name: cloudflare-ddns
            - name: CF_HOSTS
              valueFrom:
                secretKeyRef:
                  key: hosts
                  name: cloudflare-ddns
            - name: CF_RECORDTYPES
              valueFrom:
                secretKeyRef:
                  key: record-types
                  name: cloudflare-ddns
            # https://github.com/docker-hotio/docker-cloudflare-ddns#log-levels
            - name: LOG_LEVEL
              value: '3'
            - name: INTERVAL
              value: '300'
          image: ghcr.io/hotio/cloudflareddns:latest
          name: cloudflare-ddns
          # Resources allocated based on Robusta KRR output
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 20m
              memory: 10Mi
