---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - pvc.yaml

configMapGenerator:
  - name: mincraft-ketting-values
    namespace: game-servers
    files:
      - values.yaml=./values.yaml
  - name: geysermc-ketting-config
    namespace: game-servers
    files:
      - config.yml=./config/geysermc.yaml

secretGenerator:
  - name: mincraft-ketting-secret-values
    namespace: game-servers
    files:
      - values.yaml=values.enc.yaml

generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

configurations:
  - kustomizeconfig.yaml
