extraEnv:
  TZ: "Australia/Melbourne"

minecraftServer:
  serverName: Wildfire Minecraft Server
  eula: "TRUE"
  type: KETTING
  version: LATEST
  # REQUIRED: Must use for spigot plugins that are listed as available via external sites
  # pluginUrls:
  #   - https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar
  #   - https://cdn.modrinth.com/data/3wmN97b8/versions/jbQopAkk/multiverse-core-4.3.14.jar
  # spigetResources:
  #   - 19254 # ViaVersion
  #   - 34315 # Vault
  modrinth:
    projects:
      # - geyser
      # - floodgate
      # - luckperms
      - pixelmon
    downloadDependencies: required
    allowedVersionType: release
  maxPlayers: 4
  maxTickTime: -1
  gameMode: survival
  hardcore: false
  pvp: false
  worldSaveName: world
  onlineMode: true
  rcon:
    enabled: true
  motd: "Welcome to Minecraft on Kubernetes!"
  playerIdleTimeout: 10
  cheats: true
  enableLanVisibility: true
  defaultPermission: operator
  enableSSH: true
  serviceType: LoadBalancer
  extraPorts:
  - name: geysermc
    containerPort: 19132
    protocol: UDP
    service:
      enabled: true
      embedded: true
      port: 19132
  overrideServerProperties: true
  removeOldMods: false

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"

resources:
  requests:
    memory: 2Gi
    cpu: 1
    ephemeral-storage: "1Gi"

persistence:
  dataDir:
    enabled: true
    existingClaim: minecraft-ketting

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
