apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: home-system
type: Opaque
stringData:
    CROSS_SEED_API_KEY: ENC[AES256_GCM,data:Y9m2qi6a1xPCwR5UXqxK6teQgzYrAE2yb63QgFW/TLc=,iv:5WJKI3i/K4MFLRQmnXQswxk/FKQY/tKp6IU786gmCFQ=,tag:MqGP3wfLzb+sCPRm68ACWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-20T20:30:26Z"
    mac: ENC[AES256_GCM,data:xKMr/q6ZNrEvaFZbD4h9mymUlXTwldxgcSlZxuCqnL2IaDhMrLvrayZ3jDQ3bdC1/BU+oJyzu2mUKoVeEIKW6sCXKDSFsd++xExhhY1PV0AaCPxqpGEpe3OAlPY409fHt0H1gYGjwCI+RR4I5UeoQI0VISdaLrJ2Bi+ZRDIx1xY=,iv:ta6EeDrxdC+ZJrDil1xnvNIfAhrapYnbyOYGIg9Y6xA=,tag:kOUIBZ+Pkj8OIACjXMQmnw==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
