---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-router
  namespace: game-servers
spec:
  interval: 5m
  chart:
    spec:
      chart: mc-router
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  driftDetection:
    mode: enabled
  maxHistory: 3
  values:
    # Required: When not using ingress.enabled=true then must use Loadbalancer for deployment spec to render.
    service:
      type: LoadBalancer
    rconWeb:
      isAdmin: true
      passwordExistingSecret: rcon-password
      passwordKey: rcon-password
      rconHost: minecraft-bedrock-minecraft-bedrock.game-servers.svc.cluster.local
      rconPort: 19132
      rconPasswordExistingSecret: rcon-password
    extraEnv:
      TZ: Australia/Melbourne
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Service
              name: rcon-web-admin
            patch: |
              - op: add
                path: /metadata/annotations/lbipam.cilium.io~1ips
                value: ${CLUSTER_LB_MINECRAFT_RCON}
