apiVersion: v1
kind: Secret
metadata:
    name: qbtools-config-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:XUNHOz0xq4QDgjRWZpTBfJgMDrUaNL/3+OqYu8fXAOfBcrIYwInnLoASIcG8XX1Tv8aQdo5eMa4XjdSks+xYi7ya8gMQmRRHnDLYiXbFLTT3hZfyAT+beUn25djpblV2Pr79LOlN3+Ryxvs7BgSWKlS5U+BZRn2uf6A4SalsqwwmCjuoEkuOKXyioIoNOtVeQFstnHZntMnrYZz7Q1hdXLvelhTeD6rtjN5SygqExVHTd85b/p0PivZVsdvQEm4FfScbqYlOsNWheOFLhSPac7waLGNXvDPauUSa2sxybyRP1ZA7PBd8e/q9doEIqClsTzdmN/AkQ5UBSCUNqcvTWh8dUTGNYHgoPy5EejHRQ9rjj/LqOG3NTxJwgayvIrkNEy41yHveTWI170SdDB1LgSALdE4g5LldvgF9Fa/sE6xWgJOYB52c59W7ibTCJtlgRNw57DCGPdmEqChXb5621bK6tL5fU1jqycYYVnQUlphjw/06kC3S4F+oYY7pv1belf5159fToyJ73gLwNr6Zkl43JG7mo/44i6n/5ycqCUlgvF5s1LtMC7LWZTGyfLerb9QcMAJf6PZhTmpIiAB1ZS4VRicSsGeAY3vsomvXsP62PMB6jga8X7HiojdvEIrdhEAc86MQcdyP/wpPHqXmM+8QpWDNb+pvt/X3YxZhr34iZkD31GFzr+cVLapsBW1fOEECoqYl,iv:5S9bdQ6xFXunWo6sApzRA3ZsNO4gnlg8ARfWwy1N8ig=,tag:qJ5Cji7Ja+Gf3ndvKEyQGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-14T08:29:11Z"
    mac: ENC[AES256_GCM,data:B9s+MdD7bpzKa0CMfaBLrX0aKHl/TICzdOZlgICogd3AITZUxkFZUAihgu8oznR6o5Wp9mPtwfjwB4xUIz5uwCL6+FWcfE/KZOC4oOQKCVp2cbH1vQy8TC9OO/VYa3bsHQ1l85hsfkfCUIHxVpj+eu7/xUrqBp5+5RHkVDALjIA=,iv:SSMWPEDbx4NyjfEf0oKtva50KbPNZAOPoxuR4n2+QKU=,tag:/Xr5mEwQA1kCvgV+9vNNDw==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
