---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: game-servers

resources:
  - helmrelease.yaml

configMapGenerator:
  - name: mincraft-proxy-values
    namespace: game-servers
    files:
      - values.yaml=./values.yaml

generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

configurations:
  - kustomizeconfig.yaml
