---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs-system
  labels:
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/enforce: privileged
    kustomize.toolkit.fluxcd.io/prune: disabled
