minecraftServer:
  serverName: Wildfire Minecraft Server
  levelName: Wildfire
  serverPort: 19132
  eula: "TRUE"
  version: LATEST
  difficulty: peaceful
  maxPlayers: 10
  gameMode: survival
  playerIdleTimeout: 10
  cheats: true
  enableLanVisibility: true
  defaultPermission: operator
  # TODO: Consider disabling if Microsoft login failure occurs;
  # Check accounts against Minecraft account service.
  onlineMode: false
persistence:
  dataDir:
    enabled: true
    existingClaim: minecraft-bedrock
