minecraftServer:
  serverName: Wildfire Minecraft Server
  levelName: Wildfire
  serverPort: 19132
  eula: "TRUE"
  version: LATEST
  difficulty: peaceful
  maxPlayers: 10
  gameMode: survival
  playerIdleTimeout: 10
  cheats: true
  enableLanVisibility: true
  defaultPermission: operator
  enableSSH: true
persistence:
  dataDir:
    enabled: true
    existingClaim: minecraft-bedrock
