context: admin@talos-default
contexts:
    admin@talos-default:
        endpoints:
            - 192.168.50.111
            - 192.168.50.112
            - 192.168.50.113
        ca: ENC[AES256_GCM,data:4oLv6j/Pkdaca/Y/DGgz6ROPppwSYmvPwapUubafRacTr3o/PqCVCYxYlB91cdE8M8AkLMU3rvjX78Pse4AUkab/ygThjgYcrp/XXf5orN+PmTr/Iwq5zvwmkdSq99IEM7trc9XqGRelOU4upCktJLHjpvc0KnN3roMaWVpo6xtE2d0Ixse56pmjGrVh1tS5K+94HK8o5xg0zCj2FiFLyZ5UHc9V9Hp7vm5TV7FO6d7lSf3sV9fkOPGj2PIUB5lf1eDhtAZpOuQ44dci0fWA64Fl+OtA+RU39bIbzLOKiZ/dW/NEnb28xaH6V6z596pCBAQK/Q33o0H0wbi0J0Vt5x4U8ukQX6iIuhA61jUgJJ1A4QkgeX2mMHDsGngBwJ0W6toZn4dgRTbVz5ovPLgaCrFotZXY6R97yLx5A9ygZNSSNOGao0NZcok5hWwtg0AHmVNbykJdCyfzyP1Zaj72rqG/4jl1GjKlfi1FyOigtYHytGbk0b/gvu+MC07xrFI15XFoSVGL3Wk1SY7l7pPPFY77trBeO9G8USMXtqTPSfJUOGeB07yjhuu8Y1FqewM8zZDntDAqvF/PXjXS2reKXzQG5p+2cm0Ayy/aUqCN53qOtYGoeoIHRaXaPLUDqOWujvZ6vUp9WS9WsbGnCfRXCYfYBbSpQSthqM7SFAY+yS7+lHcvSSWT2hDG9LmzN72hIwEN3J0PCsterIPZScSx53KpVqsbeFj7K0FwGysY36bUNEnqfeSSU3dycmD9M5s8XZ8SOzp+iJR4/oNO/iueJWc6OnD1rgn5+pdqW9ye7CGU+n3VqheTuhwZnsCl3TqsAQAsh9T7TNf/KqlDFqhtx3y2XxBE1L+91QcunE10a2/IetDb,iv:5+LjagE1gcbZhY8RWkyr9m1DxZt1RCtwYe5bdIAzAm4=,tag:UCu1SoiLeY9p32rMz6oKHw==,type:str]
        crt: ENC[AES256_GCM,data:Q+Iqc196zrsQN2u10BRIJHo4anKNdGJsvTHIylMeEjNFykk3NknWCujY6NDXcBMyOzCHg+xTeGwI3YhuZWfEk0nAK3QQFGeuIMxB4iDVfM2fjT5feHQNuuNy1oQd+8J/YTayl462qIwZxFPF9UAnlyMO7pMTStcm5im6Yhte9mAMSprxUj/mejgGJqvHeZcO1ahoY07/lSp5agIuIi4WXqctLsM6GA3QxvU5jqsSiN+oGellWrw/pVNXYloXItqdm+s4NzGa86+oSKTAJjUe6FLoWbNb0JhIuEq9xEwwdNu2aQIYG2rNPUUOB8FWwXEcFFwJZsLbPf7laY5k1UxB3O28rBWC/TXOlSATq1eFB4yh3BVo0L91IBOyQ1if6qg/rczV0VXa/4W67SOKz3NsC37oGXEFHckFQXvnVZF+K+RFK6cwpVcZlXHLFphO0CwBiFpby63XWN4/+Zz8vSigUelEcWxPYwuEgzfDQbYqngmBfJOYrttCAGG6/3I1P+OS+d4AIySLm3OQyaDSm3P+BE01qZzqknIXTz5DqG4zmQjpsXzDlOvgbsN7/IDWw4LaoJEL6D0LORtU2M4waWM57JZ07P+kM1jr/0Hf+jYN4GVuszPdJHlB0FtP15v1Foq0wnPpGU37ZODJqjW799mndA25I6z9J4Q4LADYrmgYQyHuBXFs//6roOWLpHPUZyBmroZEaj7MeItusgZFPq4i4g6eL5QODwZDLpbiQAAJf8tdH23EvcVHwAmkR+NMzjfbB/dLHBk6zKFX+L6R3FQSjcwJHNiwQyXiCvIdg7S+R+uVJG9NBmshJw==,iv:erpHBtSGILY7JY0CgPRxDHUUbiItnm9XfQcXLw3Tm9s=,tag:SHNyWap/NRCUQPTK/n/2gg==,type:str]
        key: ENC[AES256_GCM,data:adcRW5rllZb1j5D5JqWTmLx2TaunJfCp8D3czjyrpRh2/GEiZBYpI4SMQzuifC/AMDkxlxMGj9vdb/Kmx/fT74Xai7bOLe7C+OjmlCld/JPQl1GRjiTwzWBkryGqhsqOaTL0EgCR/4tKVWKBr8sc4bewBgHOVBIEWnhZtfQ9DLGn+7afAliKTWRADoxpT8eqM20uSjHi7LxmLiZp0Vl6njtoM8rOVTtigSDP8rsIc/sudiTh,iv:yyGz/RAuRNWs06WOAqWRKFInInx1nRLQNBtaShdosXw=,tag:k6MRJtxyi2UiDsM3UHyewA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-06T00:29:12Z"
    mac: ENC[AES256_GCM,data:d0LHgVfej795AwMwnnb1FAaVy0QasQ3r/bPIBR9PFYneF06r+JkQpNcFdoYevuWnmpASl0K6gdLpIedeEacH33Nym5yaPisb42bZGUVedE705fh0Tg3A1i1cwHaIK4ffVVml89oMhm3goNgNgZcdKLU8hSlXl4+49lOg17FhdTQ=,iv:NL04iiaGr7LXnF1HzcUwybbAfhFq2Xb6BD0DIYoxlqA=,tag:5vqRyUgGF9lHRV4LLCS25A==,type:str]
    pgp:
        - created_at: "2023-03-02T05:49:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwARAA2ozZJ62IZZ/ctHFq+kC3c4KsAMf8WS1z9UacqaDbmMio
            nVD6+N24lxwAUaSqm85gDJJDw6qk9T8W+crlf0VzcHFZZaLBnVw34nTnQM+Z+PgD
            lXNvGiF77lBU453DKJkReRKSKwOzOKBvPPLo9qy2GVuqxrvWvVQgu5P2ZPwTCnbP
            FTvRrrCb/5mNN4P1twZPYp0oy8lV176ewIlZoW44U4o7bZ0dvAC/zKn0AfUr/Ym6
            z68QVIZMGq4SHc38S9Df5VStcEl36WXhG/NN9QR7By/mHlZho0gUEKGKcVrNvvNB
            5gNST3/S5R8KivqblOKAjHNgfGNko/Zse6livFj0yfx/R+ebFMtkc1XkypuGw1z7
            8EE3yIDp7G15pIENPp6ysDG8WGiuZVWTWRMSCT3AeA77JuuTLsyBd4XjacmWnFjK
            R6uh+j8TkOH53Tw4vg4VpqfF4d6WA3OkX7RLOh9mKzfXUernCSR76N95j5uTt6lu
            zUDOGdZG877XIHUMeQEnW+aVkKDJojFrt1VnbFMd62Esm3+nXmd6mQGBp93R9BN6
            na+swaivekXRGzOEXz4kjpS3tBunG+FGLx4r0mcY6EUouK2+os0fBz5zoXC0/cZF
            LdjWwEeAS7vSFRN8KMuXZ394DRbKQKe9ZnAqNbFc9saiVpsfwKNdh/y3zLXej57S
            XgHwQG/8bsgJ91eoOLPSD6AnprL+Odjt00wyCC8ZRfQRR5uDUuL3SYOhByHMprXv
            NzNDTRNljLAd5i1fIZe6U6It68gM3UPNaKqx9kj3+Zd8p/WnRbm9YZtIMnLv5qw=
            =M0cI
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ((?i)(pass|secret($|[^N])|ca|crt|key|token|^data$|^stringData$))
    version: 3.9.1
