---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-system

resources:
  - helmrelease.yaml
  - qbtools-config.enc.yaml
  - secret.enc.yaml
