apiVersion: v1
kind: Secret
metadata:
    name: qbtools-config-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:z3ZMSxJ2INlCU9Kn8pmEqKwywKHuFT3JdeBPYIzdiQoK4ucCWTMXDpTeogOHmvfwsitMOHrjFUIozchxQt5PDFAiVx+xD9FeDLD1d45rPa/2/ZzL2XcPPgCFTnCHJ2KsFmxKW6nAD2hG3E5xiEttl7UonbTKbAiK9PgKZDXIRi023Ffs9Ydv6spfGcz0T0skiLssRTo+3CXzSXcBuPEI53hsDWi8HycZMxX2jkL8aYj9dnpwWWTVtien+EsmLSVu9MAMPoYWTHnAN02p2vWtbTR6G7QT8N9mgIk+L7Z+D3GTAyJcpMiN6ZqFpN5UcDzEDg8wrg9bLROkXyOWGsRKKEE+4dwoDltCFOnCk+g8IYojEGMj8mED346YANcW31lU91jqOfT6aDPqXOP5ZfXy2D5Eoupiloho+bo8cbSd+PMqRy+exqXPzU5UYNWnz0grFXpsv2tBThltakC1QT46Yg5SAp8ooKLIZQkR97793cYc3Lsd9aN1snRBla+8a9V1tZk9V4Y0n8RjozPzLHnPOi8pCgKsuk2hzeRed7dSue+wbYnCn9JFD5PHte0CBv5OZlL+LqRvFbbKTlXKCqlu6jeQ22NhYTWWzk+WPvgp26vMGnQ/SALpPsUnNVe8ycpgURuGzwZ8boDW7m5+aiL1sDMhSdy1QYunnH2QEPoRNpvHhg0XWeq+PqeG9pRp50iS2vy6koA7,iv:zid5iy8+EGCBI9vKoKbUOZZwPIuGYLbLeaHxh47fxgo=,tag:9WdNn51M9KODoXTGR0sX4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-10T04:05:47Z"
    mac: ENC[AES256_GCM,data:zbpXjgoC0xYt09A46NeayUc99DxJCmrmz61r8WpMlonoUQMTX4yfOWBCVxr0dqqY93ULla+YkmwOd/ifYwGyGaMI3boqRHPWA8ZfJbeuATsFFUqNsIJNtmrY7BpQrDB1MyoWcdgfYH/f+Mz3PjM89RmBesudnwAilNn3gWvwyKc=,iv:iLhqsy+0qiufQg7ijy+wzQkjBP6UElZp6+768kE5tc8=,tag:+RCIdfQObWuvWGj6o7HNFA==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
