---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-schemas
  namespace: flux-system
  labels:
    substitution.flux/enabled: true
spec:
  interval: 5m
  path: "./kubernetes/namespaces/base/development/kubernetes-schemas/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
