---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-system

resources:
  - helmrelease.yaml
  - pvc.yaml

secretGenerator:
  - name: cross-seed-secret
    files:
      - config.js=secret-secret.enc.yaml

generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

configurations:
  - kustomizeconfig.yaml
