apiVersion: v1
kind: Secret
metadata:
    name: cross-seed-secret
    namespace: home-system
type: Opaque
stringData:
    config.js: ENC[AES256_GCM,data:ycoczSw0JZ3ACnQoK8hvvCimAlcBzrobjAzNbGOMXD2eTAqKo6lA0cZreIyrQFhGetwizb8qRVkm/TtwwdYdqcUMbW+XcsS5i1luQLR1n1gW0ToNrIbYQIPSkBKZzP2TAtmYtY6s/M7c0hoZDwGHkHvICj+hJPdBDtinoatCDkxXGUzAKnSkrgUKKjk8MLhoI+4kkevDtOahKQiixuB9FhI5U8B3rbnaCt0cFaqNdelYEwlqC+CwO8AhsKpNZLoiKYjkSIUyizS05VGBFkCfn6/DR83jUljiXJg3bQJK6y0Gm3qiVkijp6UeK28+Mv34CPiXABLM0yi3/IBS4nThNOsarAfLOhkTczrDXFkwn4mHiEydmUUjOVtVI96/MTKxCUCmY6q19rqic+KO8HRIUFH1Ezggugz9Bx2iQD/2ZsichVYyUOARe7KsVVk+YXH29h1EBYC9LomXM2SM6zV51Wk/Ge9mWXVIDWkkwAAxu5D/YgsPCl0eADKv93tZGAtLbRqgwoWfCevbZJJ/hGli3dojeRu5PkLLZFWKoCTYJT0dxuZHCsiH79sQd81Jggb3A47+ifxq7c+9zTH733JIsbrMAF68DzME2QCqOhDJMdXbRA05/Mf99muOPsODSw9UVcpUuEkAkycInRDEfDDHYPcHWAK8feAMO9WoIkLw9qV2HIVzvYQUlJJicU58r2pNPXa/9WEd5N0UOatPa8Kq6GqNCA8M3q5YsTWBEQskQiDCLE3DJJpsGx1/aTOWI0M0pMpZ+g4E+hA3v0FdYWh8aB/A2tMvMwqPlbue5RFa/GYMrAF31Q4S7x1DxQx+s3+QJfoUJ+KGunXtVvqLmgH55trIha1TsgvGP4xBp8q9J0bw71uHOWCMDCXjeRdrkR0qWrUpA3sj3VCVbS7om6ygmyFLz6HB6cd8XWLdctBGeHMKdDffSkJy4LCB3aKA7nbFIuLgs96dMlhKN8d4PH5lUOo5bNBADIAq6YHkmV0SrSJpVbeMuPujtwxyQ1qGhWAfE8RwnDvKaqEPNiwy9ZML9gJH6yCTfeSEUsYBsn9zF6ui2HpNu/P7W4Cw6dfYye2MJKmxPbXoLxuOQLVPPOAE2TjPwbRGyoQ9tIWAEw3YwpkuqyMTmMFuvuqJESgTYDidJWYvxicPbHt4EjCUWek5zQythbADTSFWeNUQzwCbXynsiJB+cd/lJhEkaRyc/OkNHfJ2Ytt7LZSjekhUXmOorhRRYVdSj2RnHlIXlpB7Q1BDTsx+YIQPOsZG+QZHHWYjEQMo/wpejdgQaMVgVw4hkvTelZjVh1NbmcorWwDDwTgOEq+xwnkxgtKZcG6QOZjdYqlbFCzmVCNnFwrigymEoNTg/dSv3wRBu57jcXqxGY4AazGDOCQW6TZZgFvkAtKykt1C,iv:OWgv5398UoDjvM4IiN6sbH+4OU/eP1V9m1kdEGYZras=,tag:BBMx8wT1r+eAx9BC8Bxr8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-06T22:41:16Z"
    mac: ENC[AES256_GCM,data:oZ4y0l4CygJ/RFfzj/8fN1UwqomaKRpAJEG+pY+Td8Rj0OVBYPQnVp06YapXcKYk9J9+Cd+wnab4w67dKI6+cl4e4zblDkDPmqf3i1kVhMVRgGWmIB7nAhgWjh37x3sD259luQKZV5j9ftMr/UIR+Cg5H58XWo+/dgBEtdrRnjU=,iv:o331GYiV4MokcaKviOSAoBKgWSQk0Kwh6G6mQZ4hiWY=,tag:IMY7ANroONbwTfOsgASU2Q==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
