apiVersion: v1
kind: Secret
metadata:
    name: cross-seed-secret
    namespace: home-system
type: Opaque
stringData:
    config.js: ENC[AES256_GCM,data:NczNH54loNw1aZSGKdh2JNTqG9eEHpAgFmdTG0ue28YqbBGnLYgP4VRy/t9Cf1tjwr+yBupq+fnniyjLZ5RBJ6WDfamLAE4LgkZEpWo5m44x2lfF79LuxQcM+aBnjWwcZ9n7Z8up9AD23Gyq0UsThviWtIcH1bYuArDeeJRAFZ8HR48D3aug17T1ZD227IvmmpBNWPjE0sCICuTo6PYfFUpLTUVy0YPOhVnShYt/2iTceFEQlS/brMPvx1OzQSpT16xYnKraRZ6ozn/u6laXpA+CZgQ3JSdmRlmhhIW//15CkuURwcUx6HKFgU4iGm21GLGNsPXIhd1xRPXRJjprIF/4KM+0Fn8MObiGcZDF+ieWVBsDydXCVyOds7mrD+PLwvwdaaOFJPRW2FHZwJQiS61KsUdHkyeU6+xUnto5aIiDILEBL8b6/2xJPPFprM2FXiJXndDF9ZwoUhn7jsab2jyHN+q3ZIUBiAAZthOjQjH3szDsY7T4DgLK23O3o0weYaGJ/5ToijFU/WqXoIybuKn5XZ+95Ai1SApYCcdhKGB7WAj1YNSBPRR8GZ4WkPmG/E0smYfr2aWbWbcWH09hkHy2sZP/tvc/8VdCf6ItY9tqKuGC3BMRP7Ms/IuftbrSGdoudsX9hjpr+k0TC5WA/qEO5SKzvz/FgBYdKmzm3TSWQD0ER2lhm8UoV8aKC9aw6bQabon+PzV11Y/9Sn31wJPdc88rDOkJ8LNoVmKZ4CPDJp7/1Hs1BSKGYDNcQvTOA51y8EkXCyvwT6J467yStT3jLdjFs22zquReITabY3C9R6PXl+mTxWcX+FuymX5wmubMJbe/A6SMf0bvyHoMxyoAe6ZG/UoWnoaynC7GKrj+opT1hPP+OK70NnI61vjTsF4R4aQ9R+9Y0Pg/8ycpjgcJeia/4ZOmcdGGEHS4eFkMG8lNBuL8tEK7ipBL/CFyMV3eb+56hR1KpukRtkZe7QIKObwe9Qf/KVU83oKhB+t8gvLHA5/oGc1oPWsorOmYKvI+hvIaNpzNVD8hI3hmSD+0aBjdEJI+zJmkMlHFPhlxQmF/2dDkT9w8UDg9WiNFYe+NK0/DFU/TXTe/TA+liqa5Vqb5GCbguha33FMG80CWn6EFW8pV7F4kSKWdpVjHhOXeGPJ+ghHUncFmENehZkJ+mFxj3LUJCGhErY6PmkS8KSZdN2Dm7czT1pBeS7Jg2mgkq2o8P19Bm1fk6Gs5J0ob7l2bzWI4Fzos6CDVXai6xcvcQhtJhq/NF13y1Ww3Y8Cxbc8hEXZzsySD+ZgiA0qkxTMgJRbDsGQwlWGerUC1ZY0WIGP1wAmJFB2e//eVMnwQUiCNXIXYK9Uc9DLTrO/VOe1c,iv:FSzIEY5EoGOliYBZymCUiPyYrSfFPTs6DlwSd/gpnGc=,tag:8ufnKGwWRDHZQ+qol5m3jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-10T02:10:18Z"
    mac: ENC[AES256_GCM,data:rfOP7BEjYx1XRMRAO7WMdtLjj4WlNsHG+fUPMCKjcltRR7xFl+B+jobza0Om4Zko1RwGHQjmY5YWa79WMPV5LIBCfIQlCx9dYOFuUke94iFOYlXuoJ+QlPHrt+kmBEqHxl8LCtMI22tANlzf1dkfAc7+UMVlsAgGetOjHBjX4Lo=,iv:zdmFK+dL9dgbF5/HTpqMaMldwxE/s11Rgqxxl5zyPwE=,tag:6G4wz9LApdZsLu596+SVlQ==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
