apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
  namespace: home-system
type: Opaque
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:sNPqvhe2BjFWuZUZkC/yI6+0zOFrlkhiaXAngdF4osdJonPmpUQdp5uWiDU=,iv:/yklUF2Oi3YpSOq8a0F/wqOllG2sExwIzMUfdNgqjP4=,tag:PiDsnw3s3SckEfPPeSI6pw==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:Cqt3e949+O+77OByjD2/JlFRtcr0KpHuRa1ZiBf+4ZMg2q2XpykHvHJ+tOo=,iv:yd2VboBlUpd7xyVra4CT0jap/RPE/3ELWkQ/LZtHnO8=,tag:zLuuJ+ZpyM7liSzXJSEvOg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-07-21T23:26:34Z"
  mac: ENC[AES256_GCM,data:vKhpGsC2w9Pr/fU7aPnHEIUODw5mAtVr7XVPjYfX+lhA+3hKp/P1DRU+NbT2VCrAhJTgBNuILSwMPlVCwAd4xMPGsqs+xtYDlMniG3Xfds0ZE+w/KbOOZrbD9iCrMND3UFkmKsy7LebExe7Vn8RetRZje7qKjAG/U4UNCa3p4/Y=,iv:UV9A9jPXQfegPvJ9E/AF5ot6M7OgC4E53TWA8BfBtcs=,tag:lGmzSDLMqKMaKToEIs9prQ==,type:str]
  pgp:
    - created_at: "2025-07-21T23:26:34Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAx42lmLHwoZwARAAsLnKInMhxtt2Cqe2dDi2/mG8sMSHOn/3d+uONBNPoYPa
        hLJUqwWMaKTxe3MRt0bZOm1SGaHyy5aOV/YhqMngoVQgXDjkcV4h8Jn4FAUQm2kO
        eAa76oN3+pNHPjUVo1O4NSWtWbEXQsi0gyOacbwjUQAjWKcNwOEAF5ArwdMfdsM/
        ULQKMrWeMROmJQnLTRxLwy+X8I9HFPuKMfE8k++1qDvFCzmAd2sUntBxoypSytcD
        RUU+Q+Wb6p16Pi60N1y89KM7PY52BoBW1kDdr9UuP3m/+hVhGrEkZoWw5zb7912E
        oNJ0TMEuYjh67XP5cY3acpLjTwaRFkINiWP0fqUyGRRlDHNBz9Xn7BIGh5c030Dz
        7azL52HWl5pxaCFMDI10FMXEbCOXkq0fpG0iL6tSRhrVJ32BgRtoilaUa98tGS97
        oJ+2AP5ZLkwRcxRwUNE4P/sozEpInXAYfiZBOOfbbplouJEHMGr3RzmMfBx4/zAD
        dBINuFib9aAYN8GDKFR3XZA8sSkjoZwsKqlQ79wtYJS1MyWq9WRYjT7bo30rmvpN
        O9VogjEZhVgEvSTYqGjjESZi8J0hWNpklT7EEchx7UDxpPhTQvaWBr+02ViNDQZH
        T9vRPcdzR/3xmZ65C+zLbIXcyDZ8Lo3GNritqB+5Aprw+MVVOwfqcKJdQfadUEHS
        XgG3MqsaA5uAUzZySLkBBZ3DXBw+7tPT0JE7qWL+Ok1YgZKPV89pletogIXt60DP
        AVdhBw0HeckW6RqTyx78xlJXW8oCkgJ4PJjSgso7HbNIu2ozcMiGtF3nau4bKh0=
        =nZsx
        -----END PGP MESSAGE-----
      fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
