apiVersion: v1
kind: Secret
metadata:
    name: driver-config
    namespace: democratic-csi
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:jQTkOeYvbyD5pLOtiv220DpUbYsLgdTgG2XWtkWp6dKjcDpyeDt7GjQ25TDRlmkJwZAYdJJdrhrmtWqroLoj0Hq28c5QxKBbjOkxFP6GPevNkBWpxIQJ33wEoJs+5mIV/bl5l6cebvyifuU8wRHr0rDt5yUcXrx+603Gj9d5kU5dBYaFrUEoJQwcjEsSH2HpNud+UTrfEhmUqBONSeGIOaJxrtx+HLIDX4pCKiQlMEtdZ4vzdrrMb5fkGxtitVXtUleRK2/p+DJ2XsL3J+EBdF9AdRwVt9LGXHkQ8usg41HkR76QFeL2AfWyi1jnERSWOGoveYGIiT9xsx2qdvx3de4i9ccTtBpIPJk73eTUu/eKAz9s1jW5XfXTX8kNEH85SNfp6W38PLdAEWcyd9qIERHTEF6n6MJ2IWLgnlpBOamevzCgQPbZ06HG+Mu95QF28+ZxwV0tiJT4L9s5naO4tomGN8cEYdT3bPlCuqsDL8CQq5KtwRmRg9RFEpf02QuAYw3tXvBkX+sANljl186Jsy3o+nRQYM8AckoDiEGS2qwznDKLZAWzXd0k/X18sIbg9F0E2M2ttrU8Fspl0xSCziDvvyo8k3n0Ll/dM+IGztYpYjwt4uatwm3yQLipwoJBeCCo5BKVheI8tnXueCkcYTuUx2dUwtTgg0bxfQllVwNo/S8ryWU+o1OSWxyImHk3Q5g0fP38bHvIrPNZvJwnlm+AGTSqAEeOpPqc2Jet/L5dFrfjYhW/hjq4iVNqoRxoI8+e13UZAPIXSjxtyKjaXzCzsOV1PFxSs6T3oFLgNQtCZ/rnm5Q+BKmfADEDBBL3ISUBNwiHTDxHwQOwLEzaBHMZ1ulbpFLCIMJdHMq34KJQgKWc0rIUOgr9dRpXqd1afjfMp6PYdYP1F+URh/aw24Xx5zbHxtfNebqTL4CLG6L652c+xTrfhoAiKkhhRZ6kZu0RgH7LUJ6SpJIs80CwmlbuMGHtW9AqGm868JBKXFTxt6IkY869oriOt1eApvOobMoGwCDamfhmUX17lvucyhkpduuSvAiKahI75z8ZZr0TtUKO0Cb6JTV8rTs+htQBm/GpA4PQGqXdjPzTxwmb6d6xUlQfZwBzWuwNgsv6nekLsKFyZB3IRoVaAqFFoksw/5s1E0/D0EZv3RrB3DNP2JtgxCwu2Q6vQeAS0GlCDl7pVtTs0pe/XqwVf1EwI6dLxFojyqqF6nBbMcL01ZBJcQf6fO6IARe3JTsodFP7fBMsbwGJdJURO6tuORX9yCduS3KWDy5M2XcRvN8JoBNyWHfjmnyYMzsA0mh+Qb3DV9Q4Wvee6M7mdlRS2uI8+piXR52Uy7WEC+mjdKcfkWHupEJRMq4GbKKkFVHdW9wpjqT9kBNBO5fv+LAK0oNzo8TIB9qdxq2ZXVACcBX5Qn6XIxm6waOCJ5JJwUL99bivQQ1g+LIm+U8l4AfF4FniQMflTniNltj9ly/3Ptzx3TD5SAARWqy6RDSixE2OuY31IIs3t7Ska2q4nQRMPdydR27lzFa4YeHI3F1839shu+eR4k+ZJYAT4bzjh0bt29vVveqI7r10vVrD5HKN6ySsHOodMaE4SI1HVOPDm/S4eAVpwD2tga0teIuJNrvUlIbL4r3+Gou4CErDnFLYstI6Z1RZHAMmWFJfrFO1DI4j35Bzm3ecVPxXxdtT3+Mo6wB9ZH7LHuDVwzPGzv4dgpl7/2a3z8ZLhefiKM2etVk4bjKYQjYxH6OxgqKVBG3TEOdC4XOvxiYWQD38LzkvKJd1uYolE+v08mO/sa9DnNLpZhHshMKNSJhNQeXcoYdQjU43bSbk0fHpBUsApBB6vAnX,iv:2ARxelZ07cuthfW23i1kzMYTmTc26dv9myZMTpu5lJg=,tag:O8pNVPy3GFEcbY0wBBmd6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-16T11:10:21Z"
    mac: ENC[AES256_GCM,data:n29q68KPwrMONESIxRW9j9SpT0NlBDjQaI/XA12XWB4FIOPNA2mSW5f30gP+VyoM7edQkbMeaQbpIytA3IqgDLYH0JweO1ab3GjQQuD02+9n8uWN1XTMKlyDlEQFjS70efyHEsJ3LIrmg2b9Yl/76AAzKMExso5gppu49wc+Zcs=,iv:gnZdPQUfNIAppQzsiKDOo43S2VDQuxD2e8jzUGmD2Zk=,tag:krPBCBSw0L56xUaOK4KdUA==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
