apiVersion: v1
kind: Secret
metadata:
    name: driver-config
    namespace: democratic-csi
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:cUgocBGXlA9inaiZvbC+6a5BBHglSAocnsuL90HiWkHoPsEAJOj4Bdaq3kjCTLKV9Hl1qFClgtSKr6Gv7fO7nBIJ2M7WUewdF/6n9I0ytnNSirCaJbi2BfkghpiXjORWCfZqnd/t8hL6RXBxu03xfm2PFBFW89/pu1mlG3PboC7XDEO0qqZmUti0c8+r6PND8sLHt2FdZ1YccEGuAHnOzZqMIGV5+quo8IQDhqx9XfHyWxgefp+qJDbufecaidBI2jal2yFmfQfvjxhlPUitm3A2dPq3xnjErqQFx0d6MJBY1x8FG2sOLzxRxG6rCulQqt+2F4rP9wYezWJCRKZiwtwds71kLhF93hR6CxmDZqShrdFk9Y5OZAPLaB6O6icHTTQm9Fsh9G3rlCCfY9wDb8oN7Hs8WD53Oqc4t03+sXMW6xRantHh/bzbvLoq8eXfyAaelyNLvrk/FdjDFcDqeNpUmCQMAArmQQ92jFqUlOktaIE2CprMeFIRu4t7iGeteRT2Sr2diws1aHumxbHlbUF5lmiqW6b+C3otfOutB1LT5NBDUKLCnkZfzH17TziexxPQLUZO0A5HZNcT/FqfMKZKxB92IhqUO0mwxgUbQUuC6rzY9DKT/UHIA8QOkthnnFtRBK/V/oGIw7v+EV/laWL3PxwoBZIkzrXLGzKw/iU5HsCWPO4QIQQQBwJx6ramm4OqmNxvVutrw7eKy5gpXuWV+b8VCr5x/hVY5ejciAcelAF9fqbqjRXJQgWogD6ibTKMY+NeaDh0p7KQolh7IwF5bIHleGHG/ziXMlht8HZli0AAyREoRt7wZ7VeTeTH+kT2Sr4txJy3aOTFfAIhgy7KnYY9/S+7rEZAckfLFzC4byTCnkntJochfVCp7iperKAIjPU7CRb8UMWnL+4ijRpBHc6JGyOUpeiyCcRGfCCXEW1a2zbMU3NV+JFFHpYoNubSEoaqMdOdVCB2vE5YAFzn3atPLTUNcrzbyAfPK0UvKEUbZyZMRjRbkp7KNeL9eghaMRQNfONVCmnuuPIm183HlwkBU9jsrVNHsROx49sCaSUjdscLtyDIZDu6a8rtgGrekSZ6yKNfH+V9fEno/s5iLs2szNpNuFEqueHO6OdBlP8vHRHRZ+mcJYrFxAZ9N8wKcZa0ClRK0EDLyPlbm1KyGB8GUr8hIpl9SbEJRiZ7yQMxNgrccIZ5vbOSHq9wvg6BNB8c0CbueWorI3liOEw67t5WM7S9eKgLjlDr+fUrdX1FxGy0NvinnXGIz+FNlqELDHpKGVQF29KQB+872JE8BRYWFbJ0OUNB9XmkaTnOkvcvWeir0ldA+BjDrb0dHLpmuwKdbUu80l/pqEeo5iZ7N3srbyfovpFGCgvDjnvEUDUOHDfDSO4eRGc2SjvWsyQJCpe9xDl5xQnBKLfKR3Hx3bIonuskSS81LhnU0LXxDh5f2sZOZPmrP+fY6ehcPU88hPsqsFCNUMnLETLTg4lWjV7gWdBzgVu74dO4zt2SW0ft15aI933dsVcQ0Nr6KIVTc5tYMLAT7ixfZTQNNFlIujO+bEoUFdL26/1RYVT4gBu2WYKkarOaUani5QNsQz0+PES6GSRg94GMWnWww6RX7V4Rw3cDyZXntCCeQnwbXHN9VeZBlQ5zKSZYP8Yu/lUlF0FU1DWOgKe9kCAIaPBelQVRJfE1mz1c65cDrghedS2RwCZdOW6nAlmn7p0+5Jo3NzfnONFyG4bKvc7BYZvrjWdYi/t2s0W8AjPhbkFzSXfZc+VVvOjlO3XhQ3sbsH7CMs46/cDgBS7tNOPdu+8aMtBTnCb9zVaqslvpNFgkY9eaFb/ZW2P2ow==,iv:AkGliUsaI1BW03c0+HiSJigt2IhcFx35E1dt9Q1bM8Y=,tag:O2pS3XxWhl39zPD54tj7Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-16T11:21:49Z"
    mac: ENC[AES256_GCM,data:KmoAyiP0PEr8LmIBlS8jXVdj9gHQeTL0e+5x6Ntd6DRr4F1R8RkEVDy84wPDrOTPplLRugbtjp0M2z/xt4ZQf7pWLRUICbyCOVOB8Mjs6sPhY2A9errZ6ME3N3E9CtouZv1LTfaucTxHiCc89prnyyuc2xHKSB7zbSrWTtjrRjk=,iv:1Hyb2MahIv/p35YZB3cIEUNuDJULDpMRmBmmx773XPU=,tag:FSgIG2ghS8sUQ31e5rpstg==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
