---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: democratic-csi
  namespace: democratic-csi
  labels:
    substitution.flux/enabled: true
spec:
  interval: 5m
  path: "./kubernetes/apps/base/democratic-csi/democratic-csi/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
