# Required: When not using ingress.enabled=true then must use Loadbalancer for deployment spec to render.
service:
  type: LoadBalancer
# Required: Ignored due to using virtual service.
ingress:
  enabled: true
rconWeb:
  isAdmin: true
  game: minecraft
  passwordExistingSecret: minecraft-rcon
  passwordKey: rcon-password
  rconHost: 192.168.50.182
  rconPort: 25575
  rconPasswordExistingSecret: minecraft-rcon
  rconPasswordKey: "rcon-password"
extraEnv:
  TZ: Australia/Melbourne
