---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft
  namespace: game-servers
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: truenas-iscsi-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geyser-data
  namespace: game-servers
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: truenas-iscsi-csi
