apiVersion: v1
kind: Secret
metadata:
    name: cross-seed-secret
    namespace: home-system
type: Opaque
stringData:
    data:
        AUTOBRR__SESSION_SECRET: ENC[AES256_GCM,data:1QKTOvz242wUByjnyRXQrQZjY276vugcpQS5Y2HdKk0=,iv:PdY1zm0LiMNK8J7OgbZxnboXxsS0G14wOWy0Va82bc0=,tag:vrV5NCoGNqOQSOXxpbP6uQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-06T22:50:32Z"
    mac: ENC[AES256_GCM,data:yiuMAR02W7/oyl9MsM1cV7RaFiJV6TTmkFE2g4aOSlh3BtN+56caOCzqTDDcccRPzVErBl0trkP+ipdt30R4fjZQaSiJmO/svXCQumxmfgZ3Mumuoy/OAX0jUlu+AgwpdO9X7mmGe/Wp0jQZzZwFL3O5afK2ZIwIoW/xBKslhzU=,iv:Qb7zv8EooUylqUp0H10e+P0ZHFDOPnREo487X+e7onM=,tag:SbXFaxbcrghxwD0mz9TzaQ==,type:str]
    pgp:
        - created_at: "2021-11-11T08:12:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx42lmLHwoZwAQ/+KvcM1kLDOk+RdLO+VqipVMVn1NTW0/xIIeZx6nyKduy/
            PWpmqMnZD+ALWn/VPAsW40/GJS/QFcjha6r0zwUZeeoAYX1Uj3yRx6mVmcbvlmlg
            kHFqT1b4NczIS7oM763qoCMfPwqhSxRkvqCXxf4zo5/9W85fNkxn2/E3Tc7ZIKns
            Oq4Cn5EWkl4cbDZe5zJktTrAqHBOmFEdh/JtfCuqqDE48wCk2YYUEwQD8JH3rMkJ
            v/pyNhz91HbSvJaHcvhxIulgFyVm/MX7hrU7ERA27zwl4XTg7CMG9Jx4tHKSyHw+
            o35iXuBaX5s/iPNP3ppOsvChQW5I+73wJtS+FedMSEJOt+ySH0+cV4nVXQnktVhG
            Zt6hTvZu1K8gSaDej5aYVrTmOOJqLHj5SQANa9Wooe67NLdMUE6J4MYWv4T+yXsf
            53Va7/sSfjBvpgKGtNXbTk1xv2NRD0AX+g50DZiKsedNdRYjU0YNAWYnL5S+D/la
            PHrpDxKSojgNTEwga5JzkTIV5+c9tx3Vp2Qa6XOlVa3+4zRjbWFr2fhS5hJ6S0xV
            5kKvKLc3oVlFUWir6CNS20cmCs4gjjxhq9wHPqrt4KRr0v/b/OE+F7bIUq5yLh3g
            2iq8yNwApmJRQPYmZrCUaHgEGurfia1PRZm9Xv9vRo8NJNuwCVNGLdgrB1J+RF/S
            XgGBZMp7voGHxXwtJ+QWZ47hx+jitffTGJWt4ka46olRFy370kjMN9clo6+Dtznc
            XDSTW6RKn3Nqo6O6reyvyn9wysgtwE63Hj6YLs2c4LdrFq1ZPXSkrflkLrgzIFA=
            =0xDh
            -----END PGP MESSAGE-----
          fp: 0635B8D34037A9453003FB7B93CAA682FF4C9014
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
